从 task_persistence，taskset_persistence 以及 Scheduler 中，我可以总结我的现有的错误处理的方法。在写 Scheduler 的时候，不停地进行函数抽象，也有一些心得和体会。总之都是软件工程领域的问题。

handlePromise 可以把 try catch 变为像 Go 一样的错误处理方式，即把错误和结果一起作为函数执行的结果返回.

handleAsyncCallback 把 Async 的回调函数进一步包装，即接收一个函数作为参数，包装一个 try catch 之后，再返回一个 async 函数，在 catch 中记录错误日志，这避免了抛出的异常无法看到具体的错误信息的问题。

用到了 await，有 Async 回调函数的时候，需要使用 handleAsyncCallback 进行包装；通常的 Async 函数，如果有返回值，可以用 handlePromise 来解决变量作用域的问题，如果没有返回值，而且是工具函数，可以不去管这些错误，由高层的调用者来接管错误处理。

尽可能用代码抽象出重复的代码，用有意义的命名来命名这些代码，比如，有多个位置需要用到比较类似的代码，可以抽象出函数，在不同之处，用条件分支区分开。